leftnav:
- identifier: 6aa8269e-ca9c-4fbf-8f07-6b576e31457e
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 718c0aef-f7ca-35e4-9b5b-2d5a22819b48
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 599c7bb2-2d54-3763-b755-47b1da3073ea
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: a7fc8d07-daf1-74b5-f69e-69638dc6d97d
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 642eb344-27b0-eb3b-f117-628683495484
  name: Tools
  pageRef: /pages/tools
  weight: 50
